import Head from "next/head";
import { Formik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import Link from "next/link";
import { login } from "@/pages/api/request";
import { ToastMessage } from "@/component/ToastMessage";
import { useEffect, useState } from "react";
import clsx from "clsx";

import {
  getCreds,
  getToken,
  rememberCreds,
  removeCreds,
  setToken,
} from "@/component/Constant";
import Loader from "@/component/Loader";

export default function LoginComponent({ type }: any) {
  const router = useRouter();
  const creds: any = getCreds();
  const [loading, setLoading] = useState(false);
  const [rememberCredentials, setRememberCredentials] = useState<any>();
  useEffect(() => {
    if (creds["email"] || creds["password"]) {
      setRememberCredentials(true);
    }
  }, []);

  const initialValues = {
    email: creds ? creds["email"] : "",
    password: creds ? creds["password"] : "",
  };


  const validationSchema = Yup.object({
    email: Yup.string()
      .email("Invalid email address")
      .required("Email is required"),
    password: Yup.string().required("Password is required"),
  });

  //   {
  //     "email": "eve.holt@reqres.in",
  //     "password": "cityslicka"
  // }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="row">
            <div className="col-sm-9 col-md-7 col-lg-5 mx-auto">
              <div className="card border-0 shadow rounded-3 my-5">
                <div className="card-body p-4 p-sm-5">
                  <h3 className="card-title text-center mb-5">
                    {type} Sign In
                  </h3>
                  <Formik
                    initialValues={initialValues}
                    validationSchema={validationSchema}
                    onSubmit={(values, { setSubmitting }) => {
                      setLoading(true);
                      login(values.email, values.password)
                        .then((resp) => {
                          ToastMessage("Login Successful!", "success");
                          setLoading(false);
                          setToken(resp.data.token);
                          router.push("/");
                        })
                        .catch((err) => {
                          setLoading(false);
                          ToastMessage(err.response.data.error, "error");
                        });
                    }}
                  >
                    {({
                      values,
                      errors,
                      touched,
                      handleChange,
                      handleBlur,
                      handleSubmit,
                      isSubmitting,
                    }: /* and other goodies */
                    any) => (
                      <form onSubmit={handleSubmit}>
                        <div className="mb-3">
                          <label className="form-label" htmlFor="email">
                            Email address
                          </label>
                          <div className="form-outline">
                            <input
                              type="email"
                              name="email"
                              className={clsx(
                                "form-control ",
                                {
                                  "is-invalid":
                                    touched["email"] && errors["email"],
                                },
                                {
                                  "is-valid":
                                    touched["email"] && !errors["email"],
                                }
                              )}
                              id="floatingInput"
                              placeholder="Enter your email"
                              onChange={handleChange}
                              onBlur={handleBlur}
                              value={values.email}
                            />
                            {touched.email && errors.email ? (
                              <div className="invalid-feedback">
                                {errors.email}
                              </div>
                            ) : null}
                          </div>
                        </div>
                        <div className="mb-3">
                          <label className="form-label" htmlFor="password">
                            Password
                          </label>
                          <div className="form-outline">
                            <input
                              type="password"
                              className={clsx(
                                "form-control ",
                                {
                                  "is-invalid":
                                    touched["password"] && errors["password"],
                                },
                                {
                                  "is-valid":
                                    touched["password"] && !errors["password"],
                                }
                              )}
                              id="floatingPassword"
                              placeholder="Enter your password"
                              onChange={handleChange}
                              onBlur={handleBlur}
                              value={values.password}
                              name="password"
                            />
                            {touched.password && errors.password ? (
                              <div className="invalid-feedback">
                                {errors.password}
                              </div>
                            ) : null}
                          </div>
                        </div>
                        <div className="d-flex justify-content-between">
                          <div className="form-check mb-3">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              checked={rememberCredentials}
                              id="rememberPasswordCheck"
                              onChange={(e: any) => {
                                if (e.target.checked) {
                                  rememberCreds(values);
                                  setRememberCredentials(true);
                                } else {
                                  removeCreds();
                                  setRememberCredentials(false);
                                }
                              }}
                            />
                            <label
                              className="form-check-label"
                              htmlFor="rememberPasswordCheck"
                            >
                              Remember password
                            </label>
                          </div>
                          <div className="">
                            <Link href="forgot-password" className="my-2">
                              Forgot Password
                            </Link>
                          </div>
                        </div>
                        <div className="d-grid">
                          <button
                            className="btn btn-primary btn-login text-uppercase fw-bold"
                            type="submit"
                            disabled={loading}
                          >
                            {loading && <Loader color="light" size="sm" />}
                            <span className="mx-1">Login</span>
                          </button>
                          <Link href="sign-up" className="my-2">
                            Sign Up
                          </Link>
                        </div>
                      </form>
                    )}
                  </Formik>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
